import { useEffect, useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { ActivityFeed, AnalyticsFilters, Dashboard, DashboardRange, MemberReference, SeriesPoint } from '../../types/analytics';
import { canKeepPreviousAnalytics } from '../../utils/adminAnalyticsErrors';
import { featureLabels } from '../../../supabase/functions/_shared/dashboard';
import { AdminMemberPicker, type MemberOptionsLoader } from './AdminMemberPicker';
import '../../styles/admin-dashboard.css';
export interface DashboardServices {
  dashboard(owner:string,range:DashboardRange,channel?:string,compare?:boolean,signal?:AbortSignal):Promise<Dashboard>;
  feed(filters:Pick<AnalyticsFilters,'start'|'end'|'channel'>,owner:string,signal?:AbortSignal):Promise<ActivityFeed>;
  options:MemberOptionsLoader;
}
export interface DashboardControls { range: DashboardRange; channel: string; compare: boolean }
interface Props {initialControls?: DashboardControls;onControlsChange?(controls: DashboardControls):void;owner:string;services:DashboardServices;onMemberSelect(userId:string,filters:{start:string;end:string;channel?:string}):void;onDetail(tab:string,filters:{start:string;end:string;channel?:string}):void}
const eventLabels:Record<string,string>={grading_completed:'채점 계산 완료',grading_result_viewed:'새 결과 조회',history_save_outcome:'이력 저장 응답',past_exam_file_clicked:'기출 PDF 링크 클릭',reference_opened:'참고표 열기',question_distribution_opened:'문항 분포 열기',history_viewed:'성적 이력 조회',history_trend_viewed:'성적 추이 조회',mock_saved:'사설 성적 저장 응답',admission_completed:'지원 분석 완료',admission_result_viewed:'지원 분석 결과 조회'};
const fmt=(n:number|null|undefined)=>n==null?'—':n.toLocaleString('ko-KR',{maximumFractionDigits:1});
const timestamp=(s:string)=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false});
const ranges:[DashboardRange,string][]=[['7d','7일'],['30d','30일'],['6m','6개월'],['1y','1년']];
type SeriesMetric='members'|'sessions'|'grading'|'results'|'pwa_members'|'confirmations';
const metricNames:Record<SeriesMetric,string>={members:'일평균 활성 회원 (명/일)',sessions:'일평균 이용 세션 (세션/일)',grading:'일평균 채점 완료 (회/일)',results:'일평균 결과 조회 (세션/일)',pwa_members:'일평균 PWA 활성 회원 (명/일)',confirmations:'일평균 신규 확인 회원 (명/일)'};
export function DashboardCurve({points,previous,metric='members',compact=false}:{points:SeriesPoint[];previous:SeriesPoint[];metric?:SeriesMetric;compact?:boolean}) {
  const rows=points.map((p,i)=>({x:(Date.parse(p.start)+Date.parse(p.end))/2,value:p[metric],previous:previous[i]?.[metric]??null,point:p,prior:previous[i]}));
  return <div className={compact?'':'admin-dash-chart'} style={compact?{height:56}:undefined} role="img" aria-label={metricNames[metric]}><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:10,right:10,left:compact?0:4,bottom:5}}>
    {compact&&<><XAxis type="number" dataKey="x" domain={['dataMin','dataMax']} hide/><YAxis domain={[0,'auto']} hide/></>}
    {!compact&&<><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis type="number" dataKey="x" domain={['dataMin','dataMax']} tickFormatter={n=>new Date(n).toISOString().slice(5,10)}/><YAxis domain={[0,'auto']} width={42}/><Tooltip content={({active,payload})=>{
      if(!active||!payload?.length)return null;const row=payload[0].payload as typeof rows[number];
      return <div className="admin-dash-tooltip">{row.point.start} ~ {row.point.end} (끝 경계 제외)<br/>일평균 {fmt(row.point[metric])} · {row.point.calendar_days}일<br/>구간 고유 수/총수 {fmt(row.point.coverage_status==='partial'?row.point.observed_totals[metric]:row.point.bucket_totals[metric])}{row.point.coverage_status==='partial'?' (관측분)':''}<br/>가용 완료 {row.point.available_complete_days}일{row.prior&&<><hr/>{row.prior.start} ~ {row.prior.end}<br/>이전 일평균 {fmt(row.prior[metric])}</>}</div>;
    }}/></>}
    <Line type="monotone" dataKey="value" stroke="#4f46e5" strokeWidth={2.5} connectNulls={false} dot={!compact||rows.filter(r=>r.value!==null).length===1} isAnimationActive={false}/>
    {!!previous.length&&<Line type="monotone" dataKey="previous" stroke="#94a3b8" strokeDasharray="5 4" connectNulls={false} dot={rows.filter(r=>r.previous!==null).length===1} isAnimationActive={false}/>}
  </LineChart></ResponsiveContainer></div>;
}
export function AdminDashboard(props:Props){return <DashboardPanel key={props.owner} {...props}/>;}
function DashboardPanel({owner,services,onMemberSelect,onDetail,initialControls,onControlsChange}:Props) {
  const [range,setRange]=useState<DashboardRange>(initialControls?.range||'7d'),[channel,setChannel]=useState(initialControls?.channel||''),[compare,setCompare]=useState(initialControls?.compare??true),[revision,setRevision]=useState(0),[metric,setMetric]=useState<SeriesMetric>('members');
  const [result,setResult]=useState<{key:string;data:Dashboard}|null>(null),[error,setError]=useState<{key:string;message:string}|null>(null),[busy,setBusy]=useState(true);
  const [feed,setFeed]=useState<{key:string;data:ActivityFeed}|null>(null),[feedError,setFeedError]=useState<{key:string;message:string}|null>(null),[expanded,setExpanded]=useState(false),[selected,setSelected]=useState<MemberReference|null>(null);
  const key=JSON.stringify([owner,range,channel,compare]),data=result?.key===key?result.data:null;
  useEffect(()=>{
    const c=new AbortController();
    services.dashboard(owner,range,channel,compare,c.signal).then(d=>{if(!c.signal.aborted){setResult({key,data:d});setError(null);}}).catch(e=>{if(!c.signal.aborted){setError({key,message:e instanceof Error?e.message:'통계를 불러오지 못했습니다.'});if(!canKeepPreviousAnalytics(e))setResult(null);}}).finally(()=>{if(!c.signal.aborted)setBusy(false);});
    return ()=>c.abort();
  },[owner,services,range,channel,compare,revision,key]);
  const start=data?.period.start,end=data?.period.end;
  useEffect(()=>{
    if(!start||!end)return;const c=new AbortController();
    services.feed({start,end,...(channel?{channel:channel as AnalyticsFilters['channel']}:{})},owner,c.signal).then(f=>{if(!c.signal.aborted){setFeed({key,data:f});setFeedError(null);}}).catch(e=>{if(!c.signal.aborted){setFeedError({key,message:e instanceof Error?e.message:'활동을 불러오지 못했습니다.'});if(!canKeepPreviousAnalytics(e))setFeed(null);}});
    return ()=>c.abort();
  },[owner,services,start,end,channel,revision,key]);
  const filters={start:start||'',end:end||'',...(channel?{channel}:{})};
  function selectMember(m:MemberReference|null){setSelected(m);if(m&&data)onMemberSelect(m.user_id,filters);}
  return <div className="admin-dash">
    <header className="admin-dash-header"><div><p className="admin-dash-meta">ADMIN ANALYTICS · 개요</p><h1>서비스 변화 대시보드</h1></div><button type="button" disabled={busy} onClick={()=>{setBusy(true);setError(null);setFeedError(null);setRevision(v=>v+1);}}>새로고침</button></header>
    <div className="admin-dash-filters" aria-label="대시보드 필터">{ranges.map(([v,l])=><button type="button" aria-pressed={range===v} key={v} onClick={()=>{if(v===range)return;setBusy(true);setRange(v);setExpanded(false);onControlsChange?.({range:v,channel,compare});}}>{l}</button>)}<label>실행 채널 <select value={channel} onChange={e=>{setBusy(true);setChannel(e.target.value);onControlsChange?.({range,channel:e.target.value,compare});}}><option value="">전체</option><option value="pwa">PWA</option><option value="browser">브라우저</option><option value="other">기타</option><option value="unknown">판별 불가</option></select></label><label><input type="checkbox" checked={compare} onChange={e=>{setBusy(true);setCompare(e.target.checked);onControlsChange?.({range,channel,compare:e.target.checked});}}/> 직전 기간 비교</label></div>
    {error?.key===key&&<p role="alert" className="admin-dash-error">{error.message}{data?` · 이전 조회 / 갱신 실패 (${timestamp(data.snapshot_at)})`:''}</p>}
    {!data&&busy&&<p role="status">통계를 불러오고 있습니다.</p>}
    {data&&<><p className="admin-dash-meta">분석 {data.period.start} ~ {data.period.end} · {data.period.days}일 · KST{data.previous_period&&<> / 비교 {data.previous_period.start} ~ {data.previous_period.end} · {data.previous_period.days}일</>}<br/>조회 기준 {timestamp(data.snapshot_at)}</p>
      <div className="admin-dash-status" role="status">{!data.collection.started_at?'수집 시작 전':!data.collection.enabled?'수집 비활성':data.status==='unavailable'?'조회 가능한 관측 자료 없음':data.status==='partial'?'선택 기간의 일부만 관측됨 · 수치는 관측분':'선택 기간의 자료 가용'}{compare&&data.previous_status!=='complete'?' · 이전 기간 비교 불가':''}</div>
      <div className="admin-dash-cards">{data.cards.map(c=><article className="admin-dash-card" key={c.key}><span>{c.label}</span><strong>{fmt(c.value)} <small>{c.unit}</small></strong><small>{c.status==='unsupported'?'이 채널에서 미지원':c.status==='partial'?'부분 자료 · 관측분':c.delta==null?'비교 불가':c.previous===0?c.value===0?'변화 없음':`이전 0 → ${fmt(c.value)}`:`이전 ${fmt(c.previous)} · ${c.delta>0?'+':''}${fmt(c.delta)} (${c.percent!>0?'+':''}${fmt(c.percent)}%)`}</small>{c.status!=='unsupported'&&<><DashboardCurve points={data.series} previous={compare?data.previous_series:[]} metric={c.key as SeriesMetric} compact/><small>일평균 추이 · 본문은 기간 전체 고유 수</small></>}<button type="button" aria-label={`${c.label} 상세 보기`} onClick={()=>onDetail(c.key==='pwa_members'?'pwa':['grading','results'].includes(c.key)?'grading':'members',filters)}>상세 보기</button></article>)}</div>
      <section className="admin-dash-panel"><h2>이번 기간 주요 변화</h2><ul className="admin-dash-changes">{data.changes.filter(c=>c.selected).map(c=><li key={c.metric_key}>{c.label} {fmt(c.previous)} → {fmt(c.current)} ({c.delta>0?'+':''}{fmt(c.delta)}{c.unit}){c.selection_priority===1?' · 흐름 확인 필요':''}<button type="button" onClick={()=>onDetail(c.target,filters)}>상세 보기</button></li>)}</ul>{!data.changes.some(c=>c.selected)&&<p>{!compare?'직전 기간 비교가 꺼져 있습니다.':data.status!=='complete'||data.previous_status!=='complete'?'완전한 자료가 없어 주요 변화를 비교할 수 없습니다.':'설정한 기준을 넘는 변화가 없습니다.'}</p>}</section>
      <section className="admin-dash-panel"><h2>이용 추이</h2><label>추이 지표 <select value={metric} onChange={e=>setMetric(e.target.value as SeriesMetric)}>{Object.entries(metricNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><p className="admin-dash-meta">실선 현재 · 점선 이전 · 자료 누락 구간은 선 단절 · 툴팁과 표는 실제 구간/일수 제공</p><DashboardCurve points={data.series} previous={data.previous_series} metric={metric}/><details><summary>구간별 정확한 값 보기</summary><div className="admin-dash-scroll"><table><thead><tr><th>현재 구간</th><th>전체/가용 일수</th><th>일평균</th><th>구간 고유 수/총수</th><th>이전 구간 / 일평균</th></tr></thead><tbody>{data.series.map((p,i)=><tr key={p.start}><td>{p.start} ~ {p.end}<small>끝 경계 제외</small></td><td>{p.calendar_days}/{p.available_complete_days}<small>{p.coverage_status==='complete'?'전체 가용':p.coverage_status==='partial'?'부분 자료':'미가용'}</small></td><td>{fmt(p[metric])}</td><td>{p.coverage_status==='unavailable'?'—':fmt(p.coverage_status==='partial'?p.observed_totals[metric]:p.bucket_totals[metric])}{p.coverage_status==='partial'?' (관측분)':''}</td><td>{data.previous_series[i]?<>{data.previous_series[i].start} ~ {data.previous_series[i].end}<br/>{fmt(data.previous_series[i][metric])}</>:'—'}</td></tr>)}</tbody></table></div></details></section>
      <div className="admin-dash-columns"><section className="admin-dash-panel"><h2>기능별 변화</h2><div className="admin-dash-scroll"><table><thead><tr><th>기능</th><th>행동 세션</th><th>행동 회원</th><th>행동 횟수</th><th>이전 세션</th></tr></thead><tbody>{data.status==='unavailable'?<tr><td colSpan={5}>관측 자료 없음</td></tr>:data.features.map(f=><tr key={f.feature}><td>{featureLabels[f.feature]||f.feature}{['community','chat'].includes(f.feature)&&<small>화면 진입 {fmt(f.view_sessions)} · 행동 미계측</small>}</td><td>{fmt(f.action_sessions)}</td><td>{fmt(f.action_members)}</td><td>{fmt(f.actions)}</td><td>{compare&&data.previous_status==='complete'?fmt(f.previous.action_sessions):'—'}</td></tr>)}</tbody></table></div></section><section className="admin-dash-panel"><h2>채점 입력 → 결과 관측</h2>{data.conversion?<><p>관찰 종료 {fmt(data.conversion.closed)} · 결과 관측 {fmt(data.conversion.converted)}</p><strong>{data.conversion.closed?fmt(data.conversion.converted/data.conversion.closed*100)+'%':'—'}</strong><p>진행 {fmt(data.conversion.open)} · 유예 {fmt(data.conversion.grace)} · 미확정 {fmt(data.conversion.uncertain)}</p><small>{data.previous_conversion?`이전 ${data.previous_conversion.converted}/${data.previous_conversion.closed}`:'이전 관측률 비교 불가'}</small>{(data.conversion.closed<50||(data.previous_conversion&&data.previous_conversion.closed<50))&&<p className="admin-dash-meta">표본 50 미만 · 주요 변화 후보에서 제외</p>}</>:<p>{data.period.days>90?'장기 기간 미지원 · 최근 90일 상세에서 확인':'현재 자료로 확정 관측률을 제공할 수 없습니다.'}</p>}<button type="button" onClick={()=>onDetail('grading',filters)}>채점 상세 보기</button></section></div>
      <div className="admin-dash-columns"><section className="admin-dash-panel"><h2>PWA 이용</h2>{data.pwa&&data.status!=='unavailable'?<><p>PWA 활성 세션 {fmt(data.pwa.sessions)} / 전체 {fmt(data.pwa.total_sessions)} ({data.pwa.total_sessions?fmt(data.pwa.sessions/data.pwa.total_sessions*100)+'%':'—'})</p><p>PWA만 {fmt(data.pwa.pwa_only)} · 브라우저만 {fmt(data.pwa.browser_only)} · 둘 다 {fmt(data.pwa.both)} · 기타/미확인만 {fmt(data.pwa.other_only)}</p><p>기타 세션 {fmt(data.pwa.other_sessions)} · 미확인 세션 {fmt(data.pwa.unknown_sessions)}</p><small>설치 보유 인원이 아닌 실제 실행 관측 · 전체 회원은 중복 제거</small></>:<p>{channel?'채널 필터 적용 중 · 전체 채널 비교 미지원':'관측 자료 없음'}</p>}</section><section className="admin-dash-panel"><h2>오늘 잠정 현황</h2><p>{data.today.date} · 전체 채널 · 잠정</p><p>이용 세션 {fmt(data.today.sessions)} · 채점 완료 {fmt(data.today.grading)}</p><small>마지막 새 이벤트 수락 {data.today.last_accepted_at?timestamp(data.today.last_accepted_at):'—'}<br/>오늘은 기간 증감/주요 변화에서 제외합니다.</small></section></div>
      <section className="admin-dash-panel admin-dash-feed"><h2>최근 회원 활동</h2><AdminMemberPicker owner={owner} value={selected} onChange={selectMember} loadOptions={services.options}/>{feedError?.key===key&&<p role="alert">{feedError.message}{feed?.key===key?` · 이전 조회 (${timestamp(feed.data.snapshot_at)})`:''}</p>}{feed?.key===key?<><p className="admin-dash-meta">실제 조회 {feed.data.start?timestamp(feed.data.start):'—'} ~ {feed.data.end?timestamp(feed.data.end):'—'} · {feed.data.status==='partial'?'부분 자료':feed.data.status==='unavailable'?'미가용':'가용'} · 기준 {timestamp(feed.data.snapshot_at)}</p><div className="admin-dash-scroll"><table><thead><tr><th>회원</th><th>행동</th><th>채널</th><th>수신 시각</th></tr></thead><tbody>{feed.data.items.slice(0,expanded?20:5).map(r=><tr key={r.event_id}><td><button type="button" onClick={()=>onMemberSelect(r.user_id!,filters)}>{r.name||'이름 없음'}<br/>{r.email||r.user_id}</button></td><td>{eventLabels[r.event_name]||'회원 행동'}<small>{r.attributes.outcome?({success:'성공',failed:'실패',unknown:'미확인'}[r.attributes.outcome as string]||'미확인'):''}</small></td><td>{{pwa:'PWA',browser:'브라우저',other:'기타',unknown:'판별 불가'}[r.execution_channel]}</td><td>{timestamp(r.received_at)}</td></tr>)}</tbody></table></div>{!feed.data.items.length&&<p>{feed.data.status==='unavailable'?'조회할 활동 자료가 없습니다.':'선택 기간에 관측된 회원 행동이 없습니다.'}</p>}{feed.data.items.length>5&&<button type="button" onClick={()=>setExpanded(v=>!v)}>{expanded?'5개만 보기':'최근 20개까지 보기'}</button>}</>:!feedError&&<p role="status">활동을 불러오고 있습니다.</p>}</section>
    </>}
  </div>;
}
