import type { PastExamDocument } from '../types/pastExam';

// 검증된 워터마크 PDF 78개: output/pdf/watermarked/supabase-upload-records.json
// 2027학년도는 홀수형·짝수형 구분 없는 단일 문형입니다.
export const PAST_EXAM_DOCUMENTS: PastExamDocument[] = [
  {
    year: '09예비', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '09학년도 예비시험 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-preliminary-reasoning-odd.pdf', fileName: 'LEET-2009-preliminary-reasoning-odd.pdf',
    sizeLabel: '8.3 MB',
  },
  {
    year: '09예비', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '09학년도 예비시험 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-preliminary-reasoning-even.pdf', fileName: 'LEET-2009-preliminary-reasoning-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '09예비', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '09학년도 예비시험 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-preliminary-verbal-odd.pdf', fileName: 'LEET-2009-preliminary-verbal-odd.pdf',
    sizeLabel: '8.1 MB',
  },
  {
    year: '09예비', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '09학년도 예비시험 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-preliminary-verbal-even.pdf', fileName: 'LEET-2009-preliminary-verbal-even.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2009', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2009학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-reasoning-odd.pdf', fileName: 'LEET-2009-reasoning-odd.pdf',
    sizeLabel: '9.0 MB',
  },
  {
    year: '2009', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2009학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-reasoning-even.pdf', fileName: 'LEET-2009-reasoning-even.pdf',
    sizeLabel: '1.2 MB',
  },
  {
    year: '2009', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2009학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-verbal-odd.pdf', fileName: 'LEET-2009-verbal-odd.pdf',
    sizeLabel: '8.5 MB',
  },
  {
    year: '2009', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2009학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2009-verbal-even.pdf', fileName: 'LEET-2009-verbal-even.pdf',
    sizeLabel: '1.4 MB',
  },
  {
    year: '2010', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2010학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2010-reasoning-odd.pdf', fileName: 'LEET-2010-reasoning-odd.pdf',
    sizeLabel: '7.4 MB',
  },
  {
    year: '2010', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2010학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2010-reasoning-even.pdf', fileName: 'LEET-2010-reasoning-even.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2010', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2010학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2010-verbal-odd.pdf', fileName: 'LEET-2010-verbal-odd.pdf',
    sizeLabel: '7.9 MB',
  },
  {
    year: '2010', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2010학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2010-verbal-even.pdf', fileName: 'LEET-2010-verbal-even.pdf',
    sizeLabel: '0.8 MB',
  },
  {
    year: '2011', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2011학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2011-reasoning-odd.pdf', fileName: 'LEET-2011-reasoning-odd.pdf',
    sizeLabel: '8.8 MB',
  },
  {
    year: '2011', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2011학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2011-reasoning-even.pdf', fileName: 'LEET-2011-reasoning-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2011', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2011학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2011-verbal-odd.pdf', fileName: 'LEET-2011-verbal-odd.pdf',
    sizeLabel: '8.0 MB',
  },
  {
    year: '2011', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2011학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2011-verbal-even.pdf', fileName: 'LEET-2011-verbal-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2012', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2012학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2012-reasoning-odd.pdf', fileName: 'LEET-2012-reasoning-odd.pdf',
    sizeLabel: '9.0 MB',
  },
  {
    year: '2012', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2012학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2012-reasoning-even.pdf', fileName: 'LEET-2012-reasoning-even.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2012', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2012학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2012-verbal-odd.pdf', fileName: 'LEET-2012-verbal-odd.pdf',
    sizeLabel: '9.7 MB',
  },
  {
    year: '2012', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2012학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2012-verbal-even.pdf', fileName: 'LEET-2012-verbal-even.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2013', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2013학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2013-reasoning-odd.pdf', fileName: 'LEET-2013-reasoning-odd.pdf',
    sizeLabel: '9.6 MB',
  },
  {
    year: '2013', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2013학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2013-reasoning-even.pdf', fileName: 'LEET-2013-reasoning-even.pdf',
    sizeLabel: '0.4 MB',
  },
  {
    year: '2013', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2013학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2013-verbal-odd.pdf', fileName: 'LEET-2013-verbal-odd.pdf',
    sizeLabel: '9.9 MB',
  },
  {
    year: '2013', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2013학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2013-verbal-even.pdf', fileName: 'LEET-2013-verbal-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2014', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2014학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2014-reasoning-odd.pdf', fileName: 'LEET-2014-reasoning-odd.pdf',
    sizeLabel: '8.4 MB',
  },
  {
    year: '2014', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2014학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2014-reasoning-even.pdf', fileName: 'LEET-2014-reasoning-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '2014', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2014학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2014-verbal-odd.pdf', fileName: 'LEET-2014-verbal-odd.pdf',
    sizeLabel: '9.7 MB',
  },
  {
    year: '2014', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2014학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2014-verbal-even.pdf', fileName: 'LEET-2014-verbal-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '2015', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2015학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2015-reasoning-odd.pdf', fileName: 'LEET-2015-reasoning-odd.pdf',
    sizeLabel: '8.9 MB',
  },
  {
    year: '2015', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2015학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2015-reasoning-even.pdf', fileName: 'LEET-2015-reasoning-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2015', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2015학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2015-verbal-odd.pdf', fileName: 'LEET-2015-verbal-odd.pdf',
    sizeLabel: '9.9 MB',
  },
  {
    year: '2015', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2015학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2015-verbal-even.pdf', fileName: 'LEET-2015-verbal-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '2016', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2016학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2016-reasoning-odd.pdf', fileName: 'LEET-2016-reasoning-odd.pdf',
    sizeLabel: '10.0 MB',
  },
  {
    year: '2016', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2016학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2016-reasoning-even.pdf', fileName: 'LEET-2016-reasoning-even.pdf',
    sizeLabel: '0.8 MB',
  },
  {
    year: '2016', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2016학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2016-verbal-odd.pdf', fileName: 'LEET-2016-verbal-odd.pdf',
    sizeLabel: '9.8 MB',
  },
  {
    year: '2016', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2016학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2016-verbal-even.pdf', fileName: 'LEET-2016-verbal-even.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2017', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2017학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2017-reasoning-odd.pdf', fileName: 'LEET-2017-reasoning-odd.pdf',
    sizeLabel: '8.8 MB',
  },
  {
    year: '2017', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2017학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2017-reasoning-even.pdf', fileName: 'LEET-2017-reasoning-even.pdf',
    sizeLabel: '0.4 MB',
  },
  {
    year: '2017', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2017학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2017-verbal-odd.pdf', fileName: 'LEET-2017-verbal-odd.pdf',
    sizeLabel: '9.8 MB',
  },
  {
    year: '2017', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2017학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2017-verbal-even.pdf', fileName: 'LEET-2017-verbal-even.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2018', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2018학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2018-reasoning-odd.pdf', fileName: 'LEET-2018-reasoning-odd.pdf',
    sizeLabel: '8.7 MB',
  },
  {
    year: '2018', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2018학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2018-reasoning-even.pdf', fileName: 'LEET-2018-reasoning-even.pdf',
    sizeLabel: '0.4 MB',
  },
  {
    year: '2018', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2018학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2018-verbal-odd.pdf', fileName: 'LEET-2018-verbal-odd.pdf',
    sizeLabel: '9.9 MB',
  },
  {
    year: '2018', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2018학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2018-verbal-even.pdf', fileName: 'LEET-2018-verbal-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2019', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2019학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2019-reasoning-odd.pdf', fileName: 'LEET-2019-reasoning-odd.pdf',
    sizeLabel: '10.0 MB',
  },
  {
    year: '2019', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2019학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2019-reasoning-even.pdf', fileName: 'LEET-2019-reasoning-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '2019', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2019학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2019-verbal-odd.pdf', fileName: 'LEET-2019-verbal-odd.pdf',
    sizeLabel: '9.5 MB',
  },
  {
    year: '2019', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2019학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2019-verbal-even.pdf', fileName: 'LEET-2019-verbal-even.pdf',
    sizeLabel: '1.4 MB',
  },
  {
    year: '2020', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2020학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2020-reasoning-odd.pdf', fileName: 'LEET-2020-reasoning-odd.pdf',
    sizeLabel: '8.1 MB',
  },
  {
    year: '2020', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2020학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2020-reasoning-even.pdf', fileName: 'LEET-2020-reasoning-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2020', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2020학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2020-verbal-odd.pdf', fileName: 'LEET-2020-verbal-odd.pdf',
    sizeLabel: '9.1 MB',
  },
  {
    year: '2020', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2020학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2020-verbal-even.pdf', fileName: 'LEET-2020-verbal-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2021', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2021학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2021-reasoning-odd.pdf', fileName: 'LEET-2021-reasoning-odd.pdf',
    sizeLabel: '9.9 MB',
  },
  {
    year: '2021', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2021학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2021-reasoning-even.pdf', fileName: 'LEET-2021-reasoning-even.pdf',
    sizeLabel: '0.5 MB',
  },
  {
    year: '2021', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2021학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2021-verbal-odd.pdf', fileName: 'LEET-2021-verbal-odd.pdf',
    sizeLabel: '9.0 MB',
  },
  {
    year: '2021', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2021학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2021-verbal-even.pdf', fileName: 'LEET-2021-verbal-even.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2022', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2022학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2022-reasoning-odd.pdf', fileName: 'LEET-2022-reasoning-odd.pdf',
    sizeLabel: '14.5 MB',
  },
  {
    year: '2022', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2022학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2022-reasoning-even.pdf', fileName: 'LEET-2022-reasoning-even.pdf',
    sizeLabel: '14.5 MB',
  },
  {
    year: '2022', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2022학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2022-verbal-odd.pdf', fileName: 'LEET-2022-verbal-odd.pdf',
    sizeLabel: '12.5 MB',
  },
  {
    year: '2022', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2022학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2022-verbal-even.pdf', fileName: 'LEET-2022-verbal-even.pdf',
    sizeLabel: '12.6 MB',
  },
  {
    year: '2023', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2023학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2023-reasoning-odd.pdf', fileName: 'LEET-2023-reasoning-odd.pdf',
    sizeLabel: '17.5 MB',
  },
  {
    year: '2023', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2023학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2023-reasoning-even.pdf', fileName: 'LEET-2023-reasoning-even.pdf',
    sizeLabel: '17.5 MB',
  },
  {
    year: '2023', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2023학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2023-verbal-odd.pdf', fileName: 'LEET-2023-verbal-odd.pdf',
    sizeLabel: '15.7 MB',
  },
  {
    year: '2023', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2023학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2023-verbal-even.pdf', fileName: 'LEET-2023-verbal-even.pdf',
    sizeLabel: '15.7 MB',
  },
  {
    year: '2024', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2024학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2024-reasoning-odd.pdf', fileName: 'LEET-2024-reasoning-odd.pdf',
    sizeLabel: '1.0 MB',
  },
  {
    year: '2024', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2024학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2024-reasoning-even.pdf', fileName: 'LEET-2024-reasoning-even.pdf',
    sizeLabel: '1.0 MB',
  },
  {
    year: '2024', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2024학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2024-verbal-odd.pdf', fileName: 'LEET-2024-verbal-odd.pdf',
    sizeLabel: '0.8 MB',
  },
  {
    year: '2024', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2024학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2024-verbal-even.pdf', fileName: 'LEET-2024-verbal-even.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2025', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2025학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2025-reasoning-odd.pdf', fileName: 'LEET-2025-reasoning-odd.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2025', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2025학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2025-reasoning-even.pdf', fileName: 'LEET-2025-reasoning-even.pdf',
    sizeLabel: '0.9 MB',
  },
  {
    year: '2025', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2025학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2025-verbal-odd.pdf', fileName: 'LEET-2025-verbal-odd.pdf',
    sizeLabel: '1.2 MB',
  },
  {
    year: '2025', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2025학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2025-verbal-even.pdf', fileName: 'LEET-2025-verbal-even.pdf',
    sizeLabel: '1.2 MB',
  },
  {
    year: '2026', subject: 'reasoning', examType: 'odd', format: 'pdf',
    title: '2026학년도 추리논증 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2026-reasoning-odd.pdf', fileName: 'LEET-2026-reasoning-odd.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2026', subject: 'reasoning', examType: 'even', format: 'pdf',
    title: '2026학년도 추리논증 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2026-reasoning-even.pdf', fileName: 'LEET-2026-reasoning-even.pdf',
    sizeLabel: '0.6 MB',
  },
  {
    year: '2026', subject: 'verbal', examType: 'odd', format: 'pdf',
    title: '2026학년도 언어이해 홀수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2026-verbal-odd.pdf', fileName: 'LEET-2026-verbal-odd.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2026', subject: 'verbal', examType: 'even', format: 'pdf',
    title: '2026학년도 언어이해 짝수형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2026-verbal-even.pdf', fileName: 'LEET-2026-verbal-even.pdf',
    sizeLabel: '0.7 MB',
  },
  {
    year: '2027', subject: 'reasoning', examType: 'single', format: 'pdf',
    title: '2027학년도 추리논증 단일 문형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2027-reasoning-single.pdf', fileName: 'LEET-2027-reasoning-single.pdf',
    sizeLabel: '8.5 MB',
  },
  {
    year: '2027', subject: 'verbal', examType: 'single', format: 'pdf',
    title: '2027학년도 언어이해 단일 문형 문제지',
    url: 'https://jkxxtyaanyhmjbdtybkp.supabase.co/storage/v1/object/public/past-exams/watermarked/v1/LEET-2027-verbal-single.pdf', fileName: 'LEET-2027-verbal-single.pdf',
    sizeLabel: '7.2 MB',
  },
];
